### ISSUE TITLE
RuntimeError: Error building extension 'nvdiffrast_plugin'

### ISSUE THREAD

**Issue by yejr0229** [NVlabs/nvdiffrast#194]
Here is my detailed erroe:
Traceback (most recent call last):
  File "/data/yejr/Paint-it-master/paint_it.py", line 26, in <module>
    glctx = dr.RasterizeCudaContext()
  File "/data/yejr/conda_env/paint_it/lib/python3.10/site-packages/nvdiffrast/torch/ops.py", line 177, in __init__
    self.cpp_wrapper = _get_plugin().RasterizeCRStateWrapper(cuda_device_idx)
  File "/data/yejr/conda_env/paint_it/lib/python3.10/site-packages/nvdiffrast/torch/ops.py", line 118, in _get_plugin
    torch.utils.cpp_extension.load(name=plugin_name, sources=source_paths, extra_cflags=opts, extra_cuda_cflags=opts+['-lineinfo'], extra_ldflags=ldflags, with_cuda=True, verbose=False)
  File "/data/yejr/conda_env/paint_it/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "/data/yejr/conda_env/paint_it/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1509, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/data/yejr/conda_env/paint_it/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1624, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/data/yejr/conda_env/paint_it/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1909, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'nvdiffrast_plugin': [1/5] /usr/local/cuda/bin/nvcc  -DTORCH_EXTENSION_NAME=nvdiffrast_plugin -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /data/yejr/conda_env/paint_it/lib/python3.10/site-packages/torch/include -isystem /data/yejr/conda_env/paint_it/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /data/yejr/conda_env/paint_it/lib/python3.10/site-packages/torch/include/TH -isystem /data/yejr/conda_env/paint_it/lib/python3.10/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /data/yejr/conda_env/paint_it/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_90,code=compute_90 -gencode=arch=compute_90,code=sm_90 --compiler-options '-fPIC' -DNVDR_TORCH -lineinfo -std=c++17 -c /data/yejr/conda_env/paint_it/lib/python3.10/site-packages/nvdiffrast/common/rasterize.cu -o rasterize.cuda.o 
FAILED: rasterize.cuda.o 
/usr/local/cuda/bin/nvcc  -DTORCH_EXTENSION_NAME=nvdiffrast_plugin -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /data/yejr/conda_env/paint_it/lib/python3.10/site-packages/torch/include -isystem /data/yejr/conda_env/paint_it/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /data/yejr/conda_env/paint_it/lib/python3.10/site-packages/torch/include/TH -isystem /data/yejr/conda_env/paint_it/lib/python3.10/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /data/yejr/conda_env/paint_it/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_90,code=compute_90 -gencode=arch=compute_90,code=sm_90 --compiler-options '-fPIC' -DNVDR_TORCH -lineinfo -std=c++17 -c /data/yejr/conda_env/paint_it/lib/python3.10/site-packages/nvdiffrast/common/rasterize.cu -o rasterize.cuda.o 
Segmentation fault (core dumped)
[2/5] /usr/local/cuda/bin/nvcc  -DTORCH_EXTENSION_NAME=nvdiffrast_plugin -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /data/yejr/conda_env/paint_it/lib/python3.10/site-packages/torch/include -isystem /data/yejr/conda_env/paint_it/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /data/yejr/conda_env/paint_it/lib/python3.10/site-packages/torch/include/TH -isystem /data/yejr/conda_env/paint_it/lib/python3.10/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /data/yejr/conda_env/paint_it/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_90,code=compute_90 -gencode=arch=compute_90,code=sm_90 --compiler-options '-fPIC' -DNVDR_TORCH -lineinfo -std=c++17 -c /data/yejr/conda_env/paint_it/lib/python3.10/site-packages/nvdiffrast/common/interpolate.cu -o interpolate.cuda.o 
FAILED: interpolate.cuda.o 
/usr/local/cuda/bin/nvcc  -DTORCH_EXTENSION_NAME=nvdiffrast_plugin -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /data/yejr/conda_env/paint_it/lib/python3.10/site-packages/torch/include -isystem /data/yejr/conda_env/paint_it/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /data/yejr/conda_env/paint_it/lib/python3.10/site-packages/torch/include/TH -isystem /data/yejr/conda_env/paint_it/lib/python3.10/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /data/yejr/conda_env/paint_it/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_90,code=compute_90 -gencode=arch=compute_90,code=sm_90 --compiler-options '-fPIC' -DNVDR_TORCH -lineinfo -std=c++17 -c /data/yejr/conda_env/paint_it/lib/python3.10/site-packages/nvdiffrast/common/interpolate.cu -o interpolate.cuda.o 
Segmentation fault (core dumped)
[3/5] /usr/local/cuda/bin/nvcc  -DTORCH_EXTENSION_NAME=nvdiffrast_plugin -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /data/yejr/conda_env/paint_it/lib/python3.10/site-packages/torch/include -isystem /data/yejr/conda_env/paint_it/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /data/yejr/conda_env/paint_it/lib/python3.10/site-packages/torch/include/TH -isystem /data/yejr/conda_env/paint_it/lib/python3.10/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /data/yejr/conda_env/paint_it/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_90,code=compute_90 -gencode=arch=compute_90,code=sm_90 --compiler-options '-fPIC' -DNVDR_TORCH -lineinfo -std=c++17 -c /data/yejr/conda_env/paint_it/lib/python3.10/site-packages/nvdiffrast/common/cudaraster/impl/RasterImpl.cu -o RasterImpl.cuda.o 
FAILED: RasterImpl.cuda.o 
/usr/local/cuda/bin/nvcc  -DTORCH_EXTENSION_NAME=nvdiffrast_plugin -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /data/yejr/conda_env/paint_it/lib/python3.10/site-packages/torch/include -isystem /data/yejr/conda_env/paint_it/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /data/yejr/conda_env/paint_it/lib/python3.10/site-packages/torch/include/TH -isystem /data/yejr/conda_env/paint_it/lib/python3.10/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /data/yejr/conda_env/paint_it/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_90,code=compute_90 -gencode=arch=compute_90,code=sm_90 --compiler-options '-fPIC' -DNVDR_TORCH -lineinfo -std=c++17 -c /data/yejr/conda_env/paint_it/lib/python3.10/site-packages/nvdiffrast/common/cudaraster/impl/RasterImpl.cu -o RasterImpl.cuda.o 
Segmentation fault (core dumped)
[4/5] /usr/local/cuda/bin/nvcc  -DTORCH_EXTENSION_NAME=nvdiffrast_plugin -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /data/yejr/conda_env/paint_it/lib/python3.10/site-packages/torch/include -isystem /data/yejr/conda_env/paint_it/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /data/yejr/conda_env/paint_it/lib/python3.10/site-packages/torch/include/TH -isystem /data/yejr/conda_env/paint_it/lib/python3.10/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /data/yejr/conda_env/paint_it/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_90,code=compute_90 -gencode=arch=compute_90,code=sm_90 --compiler-options '-fPIC' -DNVDR_TORCH -lineinfo -std=c++17 -c /data/yejr/conda_env/paint_it/lib/python3.10/site-packages/nvdiffrast/common/texture.cu -o texture.cuda.o 
FAILED: texture.cuda.o 
/usr/local/cuda/bin/nvcc  -DTORCH_EXTENSION_NAME=nvdiffrast_plugin -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /data/yejr/conda_env/paint_it/lib/python3.10/site-packages/torch/include -isystem /data/yejr/conda_env/paint_it/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /data/yejr/conda_env/paint_it/lib/python3.10/site-packages/torch/include/TH -isystem /data/yejr/conda_env/paint_it/lib/python3.10/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /data/yejr/conda_env/paint_it/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_90,code=compute_90 -gencode=arch=compute_90,code=sm_90 --compiler-options '-fPIC' -DNVDR_TORCH -lineinfo -std=c++17 -c /data/yejr/conda_env/paint_it/lib/python3.10/site-packages/nvdiffrast/common/texture.cu -o texture.cuda.o 
Segmentation fault (core dumped)
ninja: build stopped: subcommand failed.

**Comment by yejr0229** [comment]
After I add export MAX_JOBS=1, I get the following error:
Traceback (most recent call last):
  File "/data/yejr/Paint-it-master/paint_it.py", line 26, in <module>
    glctx = dr.RasterizeCudaContext()
  File "/root/anaconda3/envs/paint_it/lib/python3.10/site-packages/nvdiffrast/torch/ops.py", line 177, in __init__
    self.cpp_wrapper = _get_plugin().RasterizeCRStateWrapper(cuda_device_idx)
  File "/root/anaconda3/envs/paint_it/lib/python3.10/site-packages/nvdiffrast/torch/ops.py", line 118, in _get_plugin
    torch.utils.cpp_extension.load(name=plugin_name, sources=source_paths, extra_cflags=opts, extra_cuda_cflags=opts+['-lineinfo'], extra_ldflags=ldflags, with_cuda=True, verbose=False)
  File "/root/anaconda3/envs/paint_it/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "/root/anaconda3/envs/paint_it/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1509, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/root/anaconda3/envs/paint_it/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1624, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/root/anaconda3/envs/paint_it/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1909, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'nvdiffrast_plugin': [1/5] /usr/local/cuda-11.8/bin/nvcc  -ccbin /root/anaconda3/envs/paint_it/bin/x86_64-conda-linux-gnu-cc -DTORCH_EXTENSION_NAME=nvdiffrast_plugin -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /root/anaconda3/envs/paint_it/lib/python3.10/site-packages/torch/include -isystem /root/anaconda3/envs/paint_it/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /root/anaconda3/envs/paint_it/lib/python3.10/site-packages/torch/include/TH -isystem /root/anaconda3/envs/paint_it/lib/python3.10/site-packages/torch/include/THC -isystem /usr/local/cuda-11.8/include -isystem /root/anaconda3/envs/paint_it/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_90,code=compute_90 -gencode=arch=compute_90,code=sm_90 --compiler-options '-fPIC' -DNVDR_TORCH -lineinfo -std=c++17 -c /root/anaconda3/envs/paint_it/lib/python3.10/site-packages/nvdiffrast/common/cudaraster/impl/RasterImpl.cu -o RasterImpl.cuda.o 
FAILED: RasterImpl.cuda.o 
/usr/local/cuda-11.8/bin/nvcc  -ccbin /root/anaconda3/envs/paint_it/bin/x86_64-conda-linux-gnu-cc -DTORCH_EXTENSION_NAME=nvdiffrast_plugin -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /root/anaconda3/envs/paint_it/lib/python3.10/site-packages/torch/include -isystem /root/anaconda3/envs/paint_it/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /root/anaconda3/envs/paint_it/lib/python3.10/site-packages/torch/include/TH -isystem /root/anaconda3/envs/paint_it/lib/python3.10/site-packages/torch/include/THC -isystem /usr/local/cuda-11.8/include -isystem /root/anaconda3/envs/paint_it/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_90,code=compute_90 -gencode=arch=compute_90,code=sm_90 --compiler-options '-fPIC' -DNVDR_TORCH -lineinfo -std=c++17 -c /root/anaconda3/envs/paint_it/lib/python3.10/site-packages/nvdiffrast/common/cudaraster/impl/RasterImpl.cu -o RasterImpl.cuda.o 
Segmentation fault (core dumped)
ninja: build stopped: subcommand failed.

Here is my torch/cuda version:
![image](https://github.com/user-attachments/assets/c5202165-810d-40a4-b86b-265bd5eead3c)

Here is my nvcc -V:
![image](https://github.com/user-attachments/assets/c470fb6e-b8b3-4869-b592-a0cc07c1d7d1)

And these are my environment paths:
![Uploading image.png…]()

**Comment by yejr0229** [comment]
It‘s so strange that I can bulid nvdiffrast on cu113 and cu116 but cu118, can someone help me with it?

**Comment by JunrQ** [comment]
Facing the same issue.

**Comment by officialshivansh26** [comment]
Has anyone got the solution

**Comment by yejr0229** [comment]
still unsolved...

**Comment by s-laine** [comment]
We have seen `nvcc` compiler crashes before, but those have been sporadic and rare. Here, every invocation of `nvcc` seems to result in a segmentation fault, indicating an environment where the extension compilation doesn't work at all.

One possible reason I can think of is some sort of misconfiguration where different versions of Cuda toolkit end up being mixed together. E.g., the compiler binary used might be from one toolkit version, but somehow it's using libraries from another toolkit version. This is just a guess &mdash; there is no useful error message, so it's pretty much impossible to diagnose.

In any case, the problem is in the extension build environment and not nvdiffrast itself. If you're using nvdiffrast as part of larger project, you may want to ask that larger project about the proper execution environment.

**Comment by Whale-ice** [comment]
hello, has anyone solved this problem? Same hardware, same environment?

**Comment by For-Chance** [comment]
Same problem with torch2.0.1+cu118+H100.
