### ISSUE TITLE
ImportError: No module named 'nvdiffrast_plugin'

### ISSUE THREAD

**Issue by sunkymepro** [NVlabs/nvdiffrast#46]
When I run codes in ./samples/torch，there is always an error: No module named 'nvdiffrast_plugin'

Traceback (most recent call last):
  File "triangle.py", line 21, in <module>
    glctx = dr.RasterizeGLContext()
  File "/opt/conda/envs/fomm/lib/python3.7/site-packages/nvdiffrast/torch/ops.py", line 142, in __init__
    self.cpp_wrapper = _get_plugin().RasterizeGLStateWrapper(output_db, mode == 'automatic')
  File "/opt/conda/envs/fomm/lib/python3.7/site-packages/nvdiffrast/torch/ops.py", line 83, in _get_plugin
    torch.utils.cpp_extension.load(name=plugin_name, sources=source_paths, extra_cflags=opts, extra_cuda_cflags=opts, extra_ldflags=ldflags, with_cuda=True, verbose=False)
  File "/opt/conda/envs/fomm/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1091, in load
    keep_intermediates=keep_intermediates)
  File "/opt/conda/envs/fomm/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1317, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/opt/conda/envs/fomm/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1706, in _import_module_from_library
    file, path, description = imp.find_module(module_name, [path])
  File "/opt/conda/envs/fomm/lib/python3.7/imp.py", line 299, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'nvdiffrast_plugin'

It seems like that some packages are lost.
I install nvdiffrast as the instruction in document ----cd ./nvdiffrast and pip install .
I uninstall and install many times but this error still exists. I try installing in cuda10.0, torch 1.6, cuda11.1, torch 1.8.1, and Cuda 9.0, torch 1.6, but all these situations have this error. I use an Nvidia 3090 GPU.
Is there anyone who can solve this problem? Thanks.

**Comment by sunkymepro** [comment]
I install nvdiffrast in my own docker and I install dependencies as the Dockerfile, but this issue still exists.

**Comment by s-laine** [comment]
It looks like the building of plugin somehow fails silently. This should not happen with the ninja build system, and without an error message telling what went wrong, it is difficult to debug the issue.

Just to double check: Are you seeing this behavior using the provided docker setup or only in your own?

**Comment by LCY850729436** [comment]
I also meet this problem! Could someone tell me how to solve this problem?

**Comment by sunkymepro** [comment]
> > Hi @LCY850729436, can you be a bit more specific? Is this with the Docker configuration provided by us, or in a different environment? If latter, do you have the Ninja build system installed?
> 
> I have solved this problem. I think the problem should be the version adaptation of GPU to CUDA. This problem occurs when I use 2080ti, but not when I use Titan.

I use a 3090 GPU

**Comment by DoubleYanLee** [comment]
> Hi everyone,
> 
> I'm eager to help in solving this problem, but more information is needed of what exactly goes wrong. We know there are plenty of working installations out there, so something must be different in the setups that exhibit this problem.
> 
> To start, I repeat my question to everyone that experiences this problem: **Is this with the Docker configuration provided by us, or in a different environment? If latter, do you have the Ninja build system installed?**
> 
> Second, I would like to ask you to change `verbose=False` to `verbose=True` in the call to `torch.utils.cpp_extension.load` in `nvdiffrast/torch/ops.py` line 84, and share the output.
> 
> Finally, if someone has seen this problem and found a way to fix it, please share your solution. The error indicates that the nvdiffrast C++/Cuda plugin could not be loaded, and the most likely reason is that it could not be compiled. I imagine this could occur for a variety of reasons, and therefore there could be multiple different root causes for the same issue.

Hello,I've meet the same question. I  didn't use docker. my environment is CUDA10.2+pytorch1.7.1+torchvision0.8.2  I installed nvdiffrast from 'pip install .' in nvdiffrast directory .  When i run 'python pose.py',I got the same question'ImportError: No module named 'nvdiffrast_plugin'
' and a unique question like that :
<img width="691" alt="Screenshot 2021-10-30 at 9 15 16 AM" src="https://user-images.githubusercontent.com/25344948/139515118-922fbb65-f3f5-46b7-9985-abecd770ea71.png">

**Comment by s-laine** [comment]
This appears to be an incompatibility between PyTorch and the C++ compiler in the Linux distribution. A discussion [here](https://discuss.pytorch.org/t/compiler-c-not-compatible-with-the-compiler-pytorch-was-built/78018) mentions this error when trying to build PyTorch extensions on Arch Linux.

So this issue isn't specific to nvdiffrast, but prevents the building of any C++ based PyTorch extensions on your system. If PyTorch refuses to work with the compiler on the system, there unfortunately isn't anything we can do about it. We recommend using an Ubuntu distribution as that's what we have tested everything on.

**Comment by bo233** [comment]
I have solved the problem. I meet the problem on Windows, and this is due to ninja fails to compile the plugin. 
I set cl.exe`(C:\Program Files(x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30113\bin\Hostx64\x64) `and ninja.exe`(*\Anaconda\envs\*\Lib\site-packages\ninja\data\bin) `to environment variables(I'm not sure if it make sense). Then I change `verbose=False` to `verbose=True` in the call to `torch.utils.cpp_extension.load` in `nvdiffrast/torch/ops.py` line 84, and find the plugin's resource file folder`C:\Users\*\AppData\Local\torch_extensions\torch_extensions\Cache\nvdiffrast_plugin`. I `cd` to the path and try to `ninja` it, but find ninja call cl.exe, and some head files miss(in my situation is `cstddef`). Then I search the file, and add the path to environment var `INCLUDE`(`C:\Program Files(x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30113\include`), and the same as `LIB`(`C:\Program Files(x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30113\lib\x64`).
Finally the plugin is successfully complied.

**Comment by c1a1o1** [comment]
> I have solved the problem. I meet the problem on Windows, and this is due to ninja fails to compile the plugin. I set cl.exe`(C:\Program Files(x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30113\bin\Hostx64\x64) `and ninja.exe`(*\Anaconda\envs\*\Lib\site-packages\ninja\data\bin) `to environment variables(I'm not sure if it make sense). Then I change `verbose=False` to `verbose=True` in the call to `torch.utils.cpp_extension.load` in `nvdiffrast/torch/ops.py` line 84, and find the plugin's resource file folder`C:\Users\*\AppData\Local\torch_extensions\torch_extensions\Cache\nvdiffrast_plugin`. I `cd` to the path and try to `ninja` it, but find ninja call cl.exe, and some head files miss(in my situation is `cstddef`). Then I search the file, and add the path to environment var `INCLUDE`(`C:\Program Files(x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30113\include`), and the same as `LIB`(`C:\Program Files(x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30113\lib\x64`). Finally the plugin is successfully complied.
@bo233     How to include  the last two

**Comment by XCR16729438** [comment]
Got same problems on Ubuntu18.04, WSL2(Windows Subsystem for Linux), with RTX3060_laptop.
But I success to compile it on Windows10 with same computer.
_(Strange, I believed linux is always better than windows XD.)_

**Comment by s-laine** [comment]
OpenGL/Cuda interop isn't currently supported in WSL2 and thus it won't be able to run the OpenGL rasterizer in nvdiffrast.

The next release of nvdiffrast will include a Cuda-based rasterizer that sidesteps the compatibility issues on platforms where OpenGL doesn't work. The release should be out early next week.

**Comment by s-laine** [comment]
The Cuda rasterizer is now released in v0.3.0. Documentation notes [here](https://nvlabs.github.io/nvdiffrast/#rasterizing-with-cuda-vs-opengl-new).

**Comment by shengzewen** [comment]
有人在windows上成功解决这个问题了吗，或者Linux上

**Comment by icewired-yy** [comment]
I have an interesting experience when using `nvdiffrast` on Windows and I would like to share here.

 I used to download the CuDNN and add the path to the system environment variables. The way I add CuDNN to `path` create a variable name `CUDNN_HOME` pointing at the base path of CuDNN directory and add something like `%CUDMM_HOME%\bin`  into `path`. Then I found my NvDiffrast compilation failed.

So I manually compiled the nvdiffrast via `ninja --verbose` and I found that something wrong with the content of `build.ninja`, that `CUDNN_HOME` unexpectedly appeared in `build.ninja`, and pointing at a wrong path. Now I think `nvdiffrast` will automatically detect the CuDNN in system environment variables. But at that time I deleted the `CUDNN_HOME` and now everything goes well.

I think my case may not cover the general case, but I hope my sharing can help some people who makes the same mistakes as me.

**Comment by createthis** [comment]
I spent... like 10 hours trying to get this to work today on Windows 10 and Visual Studio 2022. I was able to solve the ninja compilation issues with:

```bash
# fixes  functional crtdbg.h basetsd.h
export INCLUDE="/c/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.38.33130/include:/c/Program Files (x86)/Windows Kits/10/Include/10.0.22621.0/ucrt:/c/Program Files (x86)/Windows Kits/10/Include/10.0.22621.0/shared"
# fixes  kernel32.Lib ucrt.lib
export LIB="/c/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.38.33130/lib/x64/:/c/Program Files (x86)/Windows Kits/10/Lib/10.0.22621.0/um/x64/:/c/Program Files (x86)/Windows Kits/10/Lib/10.0.22621.0/ucrt/x64"
```

There are no more errors building the plugin with ninja. However, I still see:

```
ImportError: DLL load failed while importing nvdiffrast_plugin: The specified module could not be found.
```

when building the plugin from threestudio on export.

**Comment by createthis** [comment]
I finally got past this error with another 2-1/2 hours of work on Windows 10 with Visual Studio Community 2022.

First, See previous comment for how I got `nvdiffrast_plugin` building correctly using `ninja`.

Next, I had to figure out why the import was failing. To do this, I needed to manually reproduce the problem:

```bash
# This path will be different for each system/person. I got the path from the output of the verbose=True change
cd /c/Users/jesse/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0/LocalCache/Local/torch_extensions/torch_extensions/Cache/py310_cu118/nvdiffrast_plugin
ls -al
python -vvvvvvvvvvvvvv
>>> import nvdiffrast_plugin
```
Here's a screenshot of my directory listing:
![nvdiffrast_plugin_dir_listing](https://github.com/NVlabs/nvdiffrast/assets/1695880/acb8c949-4f05-41f8-bc74-d364cff19382)

Here's a screenshot of the repro:
![nvdiffrast_plugin](https://github.com/NVlabs/nvdiffrast/assets/1695880/1c2ed669-6f38-4e88-b8fd-a2e0b652f0af)

Next, I asked myself why the import was failing when the `.pyd` file was clearly right there. After some googling, I learned a few things:
1. `.pyd` files are basically shared DLLs on Windows.
2. python will give this error if the shared DLL links other shared DLLs and those DLLs cannot be found.

So let's list the other shared DLLs:

```bash
 dumpbin //dependents ./nvdiffrast_plugin.pyd
```

Here's a screenshot of that output:
![nvdiffrast_plugin_dumpbin_dependents](https://github.com/NVlabs/nvdiffrast/assets/1695880/c6bf654a-395e-4ff4-a7a7-27a53f23119e)

Next, I painstakingly identified the location of each of these DLLs and crafted these statements to allow python to find them:

```python
import os
os.add_dll_directory(r"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\lib\x64")
os.add_dll_directory(r"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.22621.0\um\x64")
os.add_dll_directory(r"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.22621.0\ucrt\x64")

# c10.dll
os.add_dll_directory(r"C:\Users\jesse\Documents\ai\threestudio\venv\Lib\site-packages\torch\lib")

# cudart64_12.dll
os.add_dll_directory(r"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.3\bin")
```

Once this has been done, we can import the plugin successfully:
![nvdiffrast_plugin_import_working](https://github.com/NVlabs/nvdiffrast/assets/1695880/6d4cc6a8-73a5-4ce6-b4b9-10c78a681ef7)

I then solved the problem in code by adding these statements to the top of `launch.py`.

Hope this saves someone else a day of work. I hate windows! 🤣

**Comment by cyrildiagne** [comment]
Has anyone found a fix?
I'm facing the same issue with RTX 3090, and an environment setup using conda (not using Docker):
- Ubuntu 22.04
- Pytorch: 1.7.1
- CUDA: 12.2
- I've installed all the apt packages listed in the Dockerfile


I clone this repo and run `pip install .` without error:

```
Collecting numpy
  Downloading numpy-1.19.5-cp36-cp36m-manylinux2010_x86_64.whl (14.8 MB)
     |████████████████████████████████| 14.8 MB 21.6 MB/s 
Building wheels for collected packages: nvdiffrast
  Building wheel for nvdiffrast (setup.py) ... done
  Created wheel for nvdiffrast: filename=nvdiffrast-0.3.1-py3-none-any.whl size=137866 sha256=f6736342f9499bcab7d5fd651434608921671a66bc4337bde1096d18bb1a9a78
  Stored in directory: /tmp/pip-ephem-wheel-cache-4j89pp58/wheels/fd/b0/9b/ee78c398f92015d6a02b99f5db6a08c41b1a47c4be7e2e0631
Successfully built nvdiffrast
Installing collected packages: numpy, nvdiffrast
Successfully installed numpy-1.19.5 nvdiffrast-0.3.1
```

But then if I try to import:
```
import nvdiffrast.torch as dr
dr.RasterizeCudaContext(device=device)
```

I get the same issue:

**Comment by iiiCpu** [comment]
Long story short, nvdiffrast_plugin is build against `CUDA_PATH` version, not first (or the only) in `PATH`. 
So, delete nvdiffrast_plugin and set correct CUDA_PATH before run.
```
rmdir /S %userprofile%\AppData\Local\torch_extensions\torch_extensions\Cache\py310_cu121\nvdiffrast_plugin
set CUDA_PATH="C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\"
```

**Comment by iiiCpu** [comment]
> Long story short, nvdiffrast_plugin is build against `CUDA_PATH` version, not first (or the only) in `PATH`. So, delete nvdiffrast_plugin and set correct CUDA_PATH before run.
> 
> ```
> rmdir /S %userprofile%\AppData\Local\torch_extensions\torch_extensions\Cache\py310_cu121\nvdiffrast_plugin
> set CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\
> ```

@s-laine @nurpax @jannehellsten I think this should be mentioned in official documentation as one of the pre-installation steps. As many ML-activists (you included) have different CUDA versions for different projects, guessing where things went wrong might be sometimes tricky.

**Comment by Linxmotion** [comment]
I have the same problem, also 3090, looking at the comments, most people have the problem with 3090

**Comment by Picaloer** [comment]
Successfully solve the problem. Here is my full solution and referrence link:
**Problem** ImportError: DLL load failed while importing nvdiffrast_plugin: The specified module could not be found.
**Solution** Manually run ninja for nvdiffrast_plugin
1. ImportError: DLL load failed while importing nvdiffrast_plugin: The specified module could not be found.
    ```
    [https://github.com/NVlabs/nvdiffrast/issues/46#issuecomment-974756618]
    cd C:\Users\*\AppData\Local\torch_extensions\torch_extensions\Cache\nvdiffrast_plugin
    ninja
    ```
2. fatal error C1189: #error:  -- unsupported Microsoft Visual Studio version! Only the versions between 2017 and 2022 (inclusive) are supported!
	```
	[https://blog.csdn.net/HaoZiHuang/article/details/125795675]
	a. Install VS2019
	b. add cl.exe to the environment variables
	```
3. LINK : fatal error LNK1104: cannot open file 'msvcprt.lib' or other .lib files not found
   ```
   [https://www.reddit.com/r/comfyui/comments/1bf7tv1/comment/kv1dq5f/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button]
	a. Manually add the path to msvcprt.lib
	b. Run ninja again, if other .lib files are still not found, continue to add their paths
	c. The final ldflags variable in the build.ninja file:
 	ldflags = /DLL c10.lib c10_cuda.lib torch_cpu.lib torch_cuda.lib -INCLUDE:?warp_size@cuda@at@@YAHXZ torch.lib /LIBPATH:C:\Users\Picaloe\.conda\envs\instantmesh\lib\site-packages\torch\lib torch_python.lib /LIBPATH:C:\Users\Picaloe\.conda\envs\instantmesh\libs "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\lib\x64" cudart.lib "/LIBPATH:D:\Softwares\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\lib\x64" msvcprt.lib "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\Lib\10.0.22621.0\um\x64" kerbcli.lib "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\Lib\10.0.22621.0\ucrt\x64" ucrt.lib "/LIBPATH:C:\Users\Picaloe\AppData\Local\torch_extensions\torch_extensions\Cache\py310_cu121\nvdiffrast_plugin" nvdiffrast_plugin.exp "/LIBPATH:C:\Users\Picaloe\AppData\Local\torch_extensions\torch_extensions\Cache\py310_cu121\nvdiffrast_plugin" nvdiffrast_plugin.lib
   ```
Solved!

**Comment by opentld** [comment]
我解决了这个问题：

**Comment by zbclovehj** [comment]
When I was compiling nvdiffuse, the generated files in the torch.exe directory were incomplete and reported the following error

**Comment by TonyDua** [comment]
After reviewing the solutions for each of the above points and troubleshooting the issue myself, the problem arose from having multiple CUDA versions on Windows.Here is a summary of the solutions I hope will help you.

# nvdiffrast_plugin: Module Not Found

### Issue Description:

When using the `nvdiffrast` plugin, the following error occurs:

```bash
ImportError: DLL load failed while importing nvdiffrast_plugin: The specified module could not be found.
or
ImportError: No module named 'nvdiffrast_plugin'
```

### Issue Troubleshooting:

1. **Modify Detailed Compilation Log Output** Modify the `torch.ops.py` file located in your `nvdiffrast` Conda environment (e.g., `C:\ProgramData\anaconda3\envs\*\Lib\site-packages\nvdiffrast\torch\ops.py`, where `*` is your environment name). In line 125, change the `torch.utils.cpp_extension.load` function call as follows:

```python
    torch.utils.cpp_extension.load(name=plugin_name, sources=source_paths, extra_cflags=common_opts+cc_opts, extra_cuda_cflags=common_opts+['-lineinfo'], extra_ldflags=ldflags, with_cuda=True, verbose=False)

# Change verbose to True
    torch.utils.cpp_extension.load(name=plugin_name, sources=source_paths, extra_cflags=common_opts+cc_opts, extra_cuda_cflags=common_opts+['-lineinfo'], extra_ldflags=ldflags, with_cuda=True, verbose=True)
```

2.**Run Example and Check Detailed Compilation Logs**

   Run the following code to compile the `nvdiffrast_plugin` and output detailed logs:

```bash
python .\nvdiffrast\samples\torch\triangle.py --cuda
```

Observe the compilation log, especially the paths of the CUDA header files, such as:

```bash
Note: Including file:      C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include\cuda_runtime_api.h
Note: Including file:       C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include\crt/host_defines.h
Note: Including file:       C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include\builtin_types.h
......
```

You might notice that the CUDA version referenced in the header files is different from the version reported by `nvcc -V`, for example:

```bash

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Tue_Feb_27_16:28:36_Pacific_Standard_Time_2024
Cuda compilation tools, release 12.4, V12.4.99
Build cuda_12.4.r12.4/compiler.33961263_0
```

3. **Check System Environment Variable CUDA_HOME**

   Check whether the `CUDA_HOME` environment variable is correctly pointing to the current installed CUDA version (for example, v12.4, here I’m using Windows PowerShell):

```powershell
echo $env:CUDA_HOME
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8
```

### Root Cause of the Issue:

Let's summarize the findings:

1. The plugin compilation log shows that the referenced CUDA header files are from version 11.8, while `nvcc -V` reports version 12.4.
2. The files generated after plugin compilation are based on CUDA 12.4.
3. The `CUDA_HOME` environment variable in the terminal points to version 11.8.

Thus, it appears that the plugin was compiled with the incorrect version of CUDA headers.

------

### Solution:

1. **Clear Old Cache Files**
   Go to `C:\Users\YourUsername\AppData\Local\torch_extensions\torch_extensions\Cache`, find the folder named `pyXX_cuXXX` (e.g., `py311_cu124`), and delete the `nvdiffrast_plugin` directory. This folder may contain old compilation caches.

   **Tip**: If you run `ninja` inside this folder, it will tell you that there is no work to do because the build has already been compiled:

```bash
cd C:\Users\*\AppData\Local\torch_extensions\torch_extensions\Cache\py311_cu124\nvdiffrast_plugin
ninja
# ninja: no work to do.
```

2. **Modify System Environment Variable**

   You can modify the system environment variable directly or just adjust the environment variable for the current terminal session.
   **Note**: In some IDEs (like PyCharm), the environment variable changes may not take effect immediately, so it is recommended to verify using the system terminal.

  
![image-20241106115540105](https://github.com/user-attachments/assets/f1f343f5-4a6c-4c16-8ad1-832600d26e1f)


3. **Run Example Again**

   After clearing the cache and updating the `CUDA_HOME` environment variable, run the following example to check the compilation logs again:

```bash
python ./nvdiffrast/samples/torch/triangle.py --cuda
```

Observe the compilation logs and ensure that the CUDA header files are now being correctly referenced:

```bash
Note: Including file:        C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\include\cuda_fp16.hpp
Note: Including file:      C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\include\cublas_v2.h
Note: Including file:       C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\include\cublas_api.h
```

If the compilation is successful, you should see something like:

```bash
[16/16] "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64/link.exe" Buffer.o CudaRaster.o RasterImpl.cuda.o RasterImpl.o common.o rasterize.cuda.o interpolate.cuda.o texture.cuda.o texture.o antialias.cuda.o torch_bindings.o torch_rasterize.o torch_interpolate.o torch_texture.o torch_antialias.o /nologo /DLL c10.lib c10_cuda.lib torch_cpu.lib torch_cuda.lib -INCLUDE:?warp_size@cuda@at@@YAHXZ torch.lib /LIBPATH:C:\ProgramData\anaconda3\envs\tddfav3\Lib\site-packages\torch\lib torch_python.lib /LIBPATH:C:\ProgramData\anaconda3\envs\tddfav3\libs "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\lib\x64" cudart.lib /out:nvdiffrast_plugin.pyd
  Creating library nvdiffrast_plugin.lib and object nvdiffrast_plugin.exp
Loading extension module nvdiffrast_plugin...
Saving to 'tri.png'.
```
![image-20241106120340107](https://github.com/user-attachments/assets/3eebfe98-35c0-489f-9dca-c0590e32638c)


You’re done! The issue should be resolved.

**Comment by FurkanGozukara** [comment]
@TonyDua excellent writing purely amazing

Now I have few questions to you

I have CUDA path set and nvcc --version shows but echo cuda path didnt show

How do we set echo cuda path or should we set it?

![image](https://github.com/user-attachments/assets/a415818a-af1d-4549-aeac-f259ea83cc5b)

And what is difference between cuda path vs system variables?

So this main issue comes from cuda path and system variable path setup?

**Comment by ollyestn** [comment]
It is a conundrum of the century
