### ISSUE TITLE
rasterize output zero

### ISSUE THREAD

**Issue by jiaxiangshang** [NVlabs/nvdiffrast#93]
When I use the dr.rasterize, the elements in output self.rastUV_out are all zero.
`self.rastUV_out, self.rastUV_out_db = dr.rasterize(self.glctx, uv_pad.expand(batch_size, uv_pad.shape[1], uv_pad.shape[2]).contiguous(), uv_tri, resolution=[siez_tex, siez_tex], ranges=None)`

I first carefully check the pos input, which should be the ndc vertex, it seems right.
`[[ 0.6557,  0.0871,  0.0000,  1.0000]`

I also check the tri input, the triangle is valid

The cpp code is a little difficult for me to debug, can you give some suggestions?

Best
Jiaxiang

**Comment by s-laine** [comment]
This could be a number of things. Are you using Windows or Linux, and are you using the most recent version of nvdiffrast? The Windows OpenGL rasterizer used to have a bug that caused the first rendered buffer to be blank sometimes (issue #59). This was fixed a while ago, but maybe the fix doesn't work properly.

You can try using the Cuda-based rasterizer (use `RasterizeCudaContext` instead of `RasterizeGLContext`) that is included in the newest release. This should tell if the problem is on the OpenGL side or in your input data.

I can take a look at the problem as well, but I would need a complete piece of code that reproduces the issue.

**Comment by jiaxiangshang** [comment]
Hi, Samuli ,

Thank you for your quick reply and suggestions.

I use ubuntu server. I will try the newest version, but I still put the code and data here, maybe you can help me locate the bug.

Thanks again for your kind help.

Best
Jiaxiang
[server.zip](https://github.com/NVlabs/nvdiffrast/files/9741124/server.zip)

**Comment by s-laine** [comment]
The rasterizer produces valid output for me, so it looks like there is something wrong with your setup.

**Comment by jiaxiangshang** [comment]
Hi, Samuli

Thank you very much for your help, I will re-install the nvidiffraster, and I will create the rasterizer only one time,

Best 
Jiaxiang

**Comment by jiusigua** [comment]
@jiaxiangshang @s-laine   Hello, thank you very much for your discussion.
 I have encountered the same issue. When I ran the test case of jiaxiangshang provided , the output result was still 0. Could you please tell me how you resolved this?   I look forward to your reply.
Note: I have already downloaded the latest version of nvidiffrast. I am using RasterizeCudaContext instead of RasterizeGLContext, because nvidiffrast reports an error when using RasterizeGLContext. The error message is as follows:

```
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
  warnings.warn(
Traceback (most recent call last):
  File "/root/miniconda3/envs/vhap/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 2105, in _run_ninja_build
    subprocess.run(
  File "/root/miniconda3/envs/vhap/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "nvi_raster_uv.py", line 111, in <module>
    renderer.rasterize_uv(pyt_uv, pyt_tri, 256, batch_size=2)
  File "nvi_raster_uv.py", line 89, in rasterize_uv
    self.glctx = dr.RasterizeGLContext(device=device)
  File "/root/miniconda3/envs/vhap/lib/python3.8/site-packages/nvdiffrast-0.3.3-py3.8.egg/nvdiffrast/torch/ops.py", line 228, in __init__
    self.cpp_wrapper = _get_plugin(gl=True).RasterizeGLStateWrapper(output_db, mode == 'automatic', cuda_device_idx)
  File "/root/miniconda3/envs/vhap/lib/python3.8/site-packages/nvdiffrast-0.3.3-py3.8.egg/nvdiffrast/torch/ops.py", line 125, in _get_plugin
    torch.utils.cpp_extension.load(name=plugin_name, sources=source_paths, extra_cflags=common_opts+cc_opts, extra_cuda_cflags=common_opts+['-lineinfo'], extra_ldflags=ldflags, with_cuda=True, verbose=False)
  File "/root/miniconda3/envs/vhap/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1312, in load
    return _jit_compile(
  File "/root/miniconda3/envs/vhap/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1722, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/root/miniconda3/envs/vhap/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1834, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/root/miniconda3/envs/vhap/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 2121, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'nvdiffrast_plugin_gl': [1/4] c++ -MMD -MF rasterize_gl.o.d -DTORCH_EXTENSION_NAME=nvdiffrast_plugin_gl -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1017\" -isystem /root/miniconda3/envs/vhap/lib/python3.8/site-packages/torch/include -isystem /root/miniconda3/envs/vhap/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /root/miniconda3/envs/vhap/lib/python3.8/site-packages/torch/include/TH -isystem /root/miniconda3/envs/vhap/lib/python3.8/site-packages/torch/include/THC -isystem /root/miniconda3/envs/vhap/include -isystem /root/miniconda3/envs/vhap/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=1 -fPIC -std=c++17 -DNVDR_TORCH -c /root/miniconda3/envs/vhap/lib/python3.8/site-packages/nvdiffrast-0.3.3-py3.8.egg/nvdiffrast/common/rasterize_gl.cpp -o rasterize_gl.o 
FAILED: rasterize_gl.o 
c++ -MMD -MF rasterize_gl.o.d -DTORCH_EXTENSION_NAME=nvdiffrast_plugin_gl -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1017\" -isystem /root/miniconda3/envs/vhap/lib/python3.8/site-packages/torch/include -isystem /root/miniconda3/envs/vhap/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /root/miniconda3/envs/vhap/lib/python3.8/site-packages/torch/include/TH -isystem /root/miniconda3/envs/vhap/lib/python3.8/site-packages/torch/include/THC -isystem /root/miniconda3/envs/vhap/include -isystem /root/miniconda3/envs/vhap/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=1 -fPIC -std=c++17 -DNVDR_TORCH -c /root/miniconda3/envs/vhap/lib/python3.8/site-packages/nvdiffrast-0.3.3-py3.8.egg/nvdiffrast/common/rasterize_gl.cpp -o rasterize_gl.o 
In file included from /root/miniconda3/envs/vhap/lib/python3.8/site-packages/nvdiffrast-0.3.3-py3.8.egg/nvdiffrast/common/rasterize_gl.h:16,
                 from /root/miniconda3/envs/vhap/lib/python3.8/site-packages/nvdiffrast-0.3.3-py3.8.egg/nvdiffrast/common/rasterize_gl.cpp:9:
/root/miniconda3/envs/vhap/lib/python3.8/site-packages/nvdiffrast-0.3.3-py3.8.egg/nvdiffrast/common/glutil.h:36:10: fatal error: EGL/egl.h: No such file or directory
   36 | #include <EGL/egl.h>
      |          ^~~~~~~~~~~
compilation terminated.
[2/4] c++ -MMD -MF torch_rasterize_gl.o.d -DTORCH_EXTENSION_NAME=nvdiffrast_plugin_gl -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1017\" -isystem /root/miniconda3/envs/vhap/lib/python3.8/site-packages/torch/include -isystem /root/miniconda3/envs/vhap/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /root/miniconda3/envs/vhap/lib/python3.8/site-packages/torch/include/TH -isystem /root/miniconda3/envs/vhap/lib/python3.8/site-packages/torch/include/THC -isystem /root/miniconda3/envs/vhap/include -isystem /root/miniconda3/envs/vhap/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=1 -fPIC -std=c++17 -DNVDR_TORCH -c /root/miniconda3/envs/vhap/lib/python3.8/site-packages/nvdiffrast-0.3.3-py3.8.egg/nvdiffrast/torch/torch_rasterize_gl.cpp -o torch_rasterize_gl.o 
FAILED: torch_rasterize_gl.o 
c++ -MMD -MF torch_rasterize_gl.o.d -DTORCH_EXTENSION_NAME=nvdiffrast_plugin_gl -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1017\" -isystem /root/miniconda3/envs/vhap/lib/python3.8/site-packages/torch/include -isystem /root/miniconda3/envs/vhap/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /root/miniconda3/envs/vhap/lib/python3.8/site-packages/torch/include/TH -isystem /root/miniconda3/envs/vhap/lib/python3.8/site-packages/torch/include/THC -isystem /root/miniconda3/envs/vhap/include -isystem /root/miniconda3/envs/vhap/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=1 -fPIC -std=c++17 -DNVDR_TORCH -c /root/miniconda3/envs/vhap/lib/python3.8/site-packages/nvdiffrast-0.3.3-py3.8.egg/nvdiffrast/torch/torch_rasterize_gl.cpp -o torch_rasterize_gl.o 
In file included from /root/miniconda3/envs/vhap/lib/python3.8/site-packages/nvdiffrast-0.3.3-py3.8.egg/nvdiffrast/torch/../common/rasterize_gl.h:16,
                 from /root/miniconda3/envs/vhap/lib/python3.8/site-packages/nvdiffrast-0.3.3-py3.8.egg/nvdiffrast/torch/torch_rasterize_gl.cpp:12:
/root/miniconda3/envs/vhap/lib/python3.8/site-packages/nvdiffrast-0.3.3-py3.8.egg/nvdiffrast/torch/../common/glutil.h:36:10: fatal error: EGL/egl.h: No such file or directory
   36 | #include <EGL/egl.h>
      |          ^~~~~~~~~~~
compilation terminated.
[3/4] c++ -MMD -MF glutil.o.d -DTORCH_EXTENSION_NAME=nvdiffrast_plugin_gl -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1017\" -isystem /root/miniconda3/envs/vhap/lib/python3.8/site-packages/torch/include -isystem /root/miniconda3/envs/vhap/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /root/miniconda3/envs/vhap/lib/python3.8/site-packages/torch/include/TH -isystem /root/miniconda3/envs/vhap/lib/python3.8/site-packages/torch/include/THC -isystem /root/miniconda3/envs/vhap/include -isystem /root/miniconda3/envs/vhap/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=1 -fPIC -std=c++17 -DNVDR_TORCH -c /root/miniconda3/envs/vhap/lib/python3.8/site-packages/nvdiffrast-0.3.3-py3.8.egg/nvdiffrast/common/glutil.cpp -o glutil.o 
FAILED: glutil.o 
c++ -MMD -MF glutil.o.d -DTORCH_EXTENSION_NAME=nvdiffrast_plugin_gl -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1017\" -isystem /root/miniconda3/envs/vhap/lib/python3.8/site-packages/torch/include -isystem /root/miniconda3/envs/vhap/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /root/miniconda3/envs/vhap/lib/python3.8/site-packages/torch/include/TH -isystem /root/miniconda3/envs/vhap/lib/python3.8/site-packages/torch/include/THC -isystem /root/miniconda3/envs/vhap/include -isystem /root/miniconda3/envs/vhap/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=1 -fPIC -std=c++17 -DNVDR_TORCH -c /root/miniconda3/envs/vhap/lib/python3.8/site-packages/nvdiffrast-0.3.3-py3.8.egg/nvdiffrast/common/glutil.cpp -o glutil.o 
In file included from /root/miniconda3/envs/vhap/lib/python3.8/site-packages/nvdiffrast-0.3.3-py3.8.egg/nvdiffrast/common/glutil.cpp:14:
/root/miniconda3/envs/vhap/lib/python3.8/site-packages/nvdiffrast-0.3.3-py3.8.egg/nvdiffrast/common/glutil.h:36:10: fatal error: EGL/egl.h: No such file or directory
   36 | #include <EGL/egl.h>
      |          ^~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
```
